apps:
  - name: 'cluster-monitoring-backend'
    script: 'dist/index.js'
    instances: 1,
    autorestart: true
    env:
      NODE_ENV: 'development'
      HOST: 'localhost'
      PORT: 3000
    env_production:
      NODE_ENV: 'production'
      HOST: 'localhost'
      PORT: 3000
